### ISSUE TITLE
Issue installing this gem

### ISSUE THREAD

**Issue by hqbeyers** [msevestre/monologue_image_upload#8]
Hi, I cannot seem to install this gem. I copied the exact line into my Gemfile as instructed. I get the following error:

Retrying `git clone 'git@github.com:msevestre/monologue_image_upload.git' "mydirectory/git/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:msevestre/monologue_image_upload.git' "/mydirectory/git/monologue_image_upload-34d6c03dbe659e9454eede0dabfb247af27e98c9" --bare --no-hardlinks --quiet` in directory /mydirectory has failed.Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by msevestre** [comment]
Please use
gem 'monologue_image_upload', :git => "https://github.com/msevestre/monologue_image_upload.git"

Instead
